### Import packages

In [2]:
import pandas as pd         
import numpy as np          
from datetime import date

### Read in Data

In [46]:
hospitals = pd.read_csv('data/CaliforniaHospitalData.csv')                 # hospital data
personnel = pd.read_csv('data/CaliforniaHospitalData_Personnel.txt', delimiter='\t')  # personnel data (tab-delimited)

### Merge Data

In [54]:
full_data = pd.merge(personnel, hospitals, on='HospitalID', how='left')  # left join on HospitalID
full_data

,HospitalID,Work_ID,LastName,FirstName,Gender,PositionID,PositionTitle,Compensation,MaxTerm,StartDate,...,TypeControl,Teaching,DonorType,NoFTE,NetPatRev,InOperExp,OutOperExp,OperRev,OperInc,AvlBeds
0,35665,351131,Cherukuri,Dileep,M,4,Safety Inspection Member,23987,2,1/1/2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12145,756481,Rodriguez,Jose,M,1,Regional Representative,46978,4,1/1/2009,...,Non Profit,Small/Rural,Charity,345.0,136156.69130,3.344754e+07,2.034860e+07,53351748.0,-444391.0,99.0
2,45771,756481,Rodriguez,Jose,M,1,Regional Representative,46978,4,1/1/2011,...,District,Small/Rural,Charity,219.0,52983.85792,8.074273e+06,1.299607e+07,19484351.0,-1585993.0,76.0
3,43353,756481,Rodriguez,Jose,M,4,Safety Inspection Member,23987,2,1/1/2011,...,Non Profit,Small/Rural,Charity,55.0,14172.24044,1.436471e+06,3.989894e+06,5235317.0,-191048.0,12.0
4,17718,811240,Charles,Kenneth,M,1,Regional Representative,46978,4,1/1/2009,...,Non Profit,Small/Rural,Charity,215.5,123480.27050,2.200350e+07,2.241005e+07,45769108.0,1355554.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,33283,704360,Frank,Vernon,M,1,Regional Representative,46978,4,1/1/2012,...,Non Profit,Small/Rural,Charity,353.0,173227.48630,2.864761e+07,3.962144e+07,64464737.0,-3804313.0,25.0
60,33242,704360,Frank,Vernon,M,4,Safety Inspection Member,23987,2,1/1/2011,...,Non Profit,Small/Rural,Charity,318.0,161745.22400,3.064671e+07,3.027761e+07,59669536.0,-1254783.0,42.0
61,46342,768057,Tanner,Patricia,F,3,Acting Director,248904,8,1/1/2011,...,District,Small/Rural,Charity,160.0,65792.42623,1.534131e+07,7.916540e+06,24164520.0,906670.0,131.0
62,43437,768057,Tanner,Patricia,F,1,Regional Representative,46978,4,1/1/2010,...,District,Small/Rural,Charity,121.0,17566.92896,2.890228e+06,4.578888e+06,6677960.0,-791156.0,37.0
63,29823,768057,Tanner,Patricia,F,3,Acting Director,248904,8,1/1/2009,...,Non Profit,Small/Rural,Charity,168.0,51726.49180,9.022366e+06,1.040251e+07,19445901.0,21025.0,48.0

### Exporting Data

In [81]:
filtered = full_data[
    (full_data['Teaching'] == 'Small/Rural') & 
    (full_data['AvlBeds'] >= 15) &
    (full_data['OperInc'] >= 0)
]
# Export as tab-delimited without index
filtered.to_csv('data/hospital_data_new.txt', sep='\t', index=False)  # save filtered data

### Renaming Columns

In [77]:
hospital_data_new = pd.read_csv('data/hospital_data_new.txt', delimiter='\t')  # read tab-delimited file

hospital_data_new = hospital_data_new.rename(columns={
    'NoFTE': 'FullTimeCount',
    'NetPatRev': 'NetPatientRevenue',
    'InOperExp': 'InpatientOperExp',
    'OutOperExp': 'OutpatientOperExp',
    'OperRev': 'Operating_Revenue',
    'OperInc': 'Operating_Income'
}) ### Rename columns

### Inserting Records

In [91]:
new_rows = hospital_data_new[hospital_data_new['Name'].isin([
    'Tahoe Forest Hospital District',
    'Hi-Desert Medical Center'
])].copy()

new_rows['FirstName'] = 'Kevin'  # first name
new_rows['LastName'] = 'Good'    # last name
new_rows['StartDate'] = date.today().isoformat()  # today’s date
new_rows['PositionTitle'] = ['Regional Representative', 'State Board Representative']
new_rows['Compensation'] = [46978, 89473]
new_rows['MaxTerm'] = [4, 3]

# Combine with existing data
new_merge = pd.concat([hospital_data_new, new_rows], ignore_index=True)  # insert new records

### Filtering Data

In [95]:
filtered_hospitals = new_merge[
    (new_merge['TypeControl'] == 'Non Profit') &
    (new_merge['FullTimeCount'] > 250) &
    (new_merge['NetPatientRevenue'] >= 109000)
]

# Drop employee-related columns
filtered_hospitals = filtered_hospitals.drop(columns=[
    'FirstName', 'LastName', 'Gender', 'PositionID',
    'PositionTitle', 'Compensation', 'MaxTerm',
    'StartDate', 'Phone', 'Email'
])
filtered_hospitals

,HospitalID,Work_ID,Name,Zip,Website,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,Operating_Revenue,Operating_Income,AvlBeds
1,17736,811240,Sierra Nevada Memorial Hospital,95945,www.snmh.org,Non Profit,Small/Rural,Charity,524.5,295579.2350,5.669283e+07,50264174.90,109748000.0,2791000.0,121.0
6,13738,229849,St. Mary Medical Center,92307-2206,www.stmary4health.com,Non Profit,Small/Rural,Charity,1216.0,540975.1175,1.251283e+08,66801544.65,199873795.0,7943967.0,186.0
8,46348,664583,Barton Memorial Hospital,96150,www.bartonhealth.org,Non Profit,Small/Rural,Charity,750.0,335179.5574,5.358904e+07,67030147.91,126303054.0,5683870.0,119.0
11,17741,363672,St. Elizabeth Community Hospital,96080,redbluff.mercy.org/index.htm,Non Profit,Small/Rural,Charity,397.5,232503.0191,3.668289e+07,36739260.30,85808509.0,12386360.0,66.0
12,20231,966527,Hanford Community Medical Center,93230-3513,www.hanfordhealth.com,Non Profit,Small/Rural,Charity,777.0,363127.5956,5.370467e+07,70582081.57,134067466.0,9780718.0,121.0
14,20266,231581,Sonora Regional Medical Center - greenley,95370,www.sonorahospital.org,Non Profit,Small/Rural,Charity,779.0,367540.6639,6.822885e+07,69968859.17,139302913.0,1105205.0,152.0
19,46996,856720,Ridgecrest Regional Hospital,93555,www.rrh.org,Non Profit,Small/Rural,Charity,400.0,139170.3798,2.338557e+07,24661355.90,51087341.0,3040415.0,55.0
20,20277,398103,Ukiah Valley Medical Center,95482,www.uvmc.org,Non Profit,Small/Rural,Charity,503.5,214516.4481,3.270922e+07,43571851.35,79005075.0,2724001.0,65.0
22,33251,411280,Sutter Coast Hospital,95531-8359,www.suttercoast.org,Non Profit,Small/Rural,Charity,363.0,172398.8579,2.278128e+07,38582723.52,63398216.0,2034214.0,59.0
24,38798,909709,Goleta Valley Cottage Hospital,93111,www.sbch.org,Non Profit,Small/Rural,Charity,288.0,335179.5574,5.358904e+07,67030147.91,126303054.0,5683870.0,119.0

In [99]:
# Filter for Regional Representatives with Operating_Income > 100,000
regional_reps = new_merge[
    (new_merge['PositionTitle'] == 'Regional Representative') &
    (new_merge['Operating_Income'] > 100000)
]
regional_reps

,HospitalID,Work_ID,LastName,FirstName,Gender,PositionID,PositionTitle,Compensation,MaxTerm,StartDate,...,TypeControl,Teaching,DonorType,FullTimeCount,NetPatientRevenue,InpatientOperExp,OutpatientOperExp,Operating_Revenue,Operating_Income,AvlBeds
0,17718,811240,Charles,Kenneth,M,1,Regional Representative,46978,4,1/1/2009,...,Non Profit,Small/Rural,Charity,215.5,123480.27050,2.200350e+07,2.241005e+07,45769108.0,1355554.0,60.0
7,38802,310431,Dong,HongWei,F,1,Regional Representative,46978,4,1/1/2010,...,Non Profit,Small/Rural,Charity,67.0,28773.45355,1.780969e+06,8.235088e+06,10751114.0,735057.0,20.0
8,46348,664583,Paanua,Kaaluai,M,1,Regional Representative,46978,4,1/1/2011,...,Non Profit,Small/Rural,Charity,750.0,335179.55740,5.358904e+07,6.703015e+07,126303054.0,5683870.0,119.0
14,20266,231581,Adams,Sandy,F,1,Regional Representative,46978,4,1/1/2009,...,Non Profit,Small/Rural,Charity,779.0,367540.66390,6.822885e+07,6.996886e+07,139302913.0,1105205.0,152.0
16,19868,318165,Coulter,Tracy,F,1,Regional Representative,46978,4,1/1/2010,...,Non Profit,Small/Rural,Charity,180.0,59504.62295,1.195530e+07,1.032680e+07,22492281.0,210180.0,103.0
20,20277,398103,Johanson,Sandy,F,1,Regional Representative,46978,4,1/1/2012,...,Non Profit,Small/Rural,Charity,503.5,214516.44810,3.270922e+07,4.357185e+07,79005075.0,2724001.0,65.0
23,37393,909709,Iwata,Akira,M,1,Regional Representative,46978,4,1/1/2011,...,Investor,Small/Rural,Charity,262.0,116797.83060,1.368450e+07,1.515999e+07,42845642.0,14001153.0,42.0
24,38798,909709,Iwata,Akira,M,1,Regional Representative,46978,4,1/1/2011,...,Non Profit,Small/Rural,Charity,288.0,335179.55740,5.358904e+07,6.703015e+07,126303054.0,5683870.0,119.0

### Convert Date-Time Data

In [104]:
# Convert StartDate to datetime (handles both mm/dd/yyyy and ISO formats)
new_merge['StartDate'] = pd.to_datetime(new_merge['StartDate'], format='mixed')

# Confirm data types
print(new_merge.dtypes)  # StartDate should now be datetime64

# Preview first 5 converted dates
print(new_merge['StartDate'].head())

HospitalID                    int64
Work_ID                       int64
LastName                     object
FirstName                    object
Gender                       object
PositionID                    int64
PositionTitle                object
Compensation                  int64
MaxTerm                       int64
StartDate            datetime64[ns]
Phone                        object
Email                        object
Name                         object
Zip                          object
Website                      object
TypeControl                  object
Teaching                     object
DonorType                    object
FullTimeCount               float64
NetPatientRevenue           float64
InpatientOperExp            float64
OutpatientOperExp           float64
Operating_Revenue           float64
Operating_Income            float64
AvlBeds                     float64
dtype: object
0   2009-01-01
1   2006-01-01
2   2010-01-01
3   2010-01-01
4   2005-01-01
Name: StartDate, dtype: datetime64[ns]

Reference: https://chatgpt.com/c/67fdd164-8e18-8001-87be-e49b2e639e59